/**
 * pdf-lib rewrites a document in JavaScript memory, holding both the source and
 * generated bytes plus its parsed object graph. Keep that work away from mobile
 * heaps once the source is large enough to make an OS kill plausible. Viewing
 * remains native and is intentionally not subject to this limit.
 */
export const MAX_MOBILE_FLATTEN_BYTES = 64 * 1024 * 1024;

export function canFlattenOnMobile(
  sizeBytes: number | undefined,
  limitBytes = MAX_MOBILE_FLATTEN_BYTES,
): boolean {
  return sizeBytes === undefined || (
    Number.isFinite(sizeBytes)
    && sizeBytes >= 0
    && sizeBytes <= limitBytes
  );
}

export function bytesToWholeMiB(bytes: number): number {
  return Math.floor(bytes / (1024 * 1024));
}
